#!/usr/bin/env python3
"""Generates Koyak's Android launcher icon and native splash assets.

The mark is a "torn K": Plus Jakarta Sans ExtraBold K in brand green, cut by
a slanted gap across the top. Outlines come straight from the bundled font,
so the vector assets stay sharp at every size.

Usage (from the repo root):
    python3 tool/generate_brand_assets.py

Needs: fontTools, Pillow.
"""

from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageChops, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / 'android/app/src/main/res'
FONT = ROOT / 'assets/fonts/PlusJakartaSans-ExtraBold.ttf'

BACKGROUND = '#12131C'
GREEN = '#34D399'
MUTED = '#9CA3AF'

# Adaptive icon canvas is 108dp; the launcher masks it to the central ~66dp.
CANVAS = 108.0
MARK_HEIGHT = 44.0
SPLASH_MARK_HEIGHT = 30.0

# The tear: a gap running from 46% down on the left to 22% down on the right
# of the K's bounding box, 7.5% of its height wide. Placed so the V between
# the stem and upper arm ends inside the gap (no leftover notch) while the
# gap still clears the crotch where the two arms meet.
CUT_LEFT, CUT_RIGHT, CUT_GAP = 0.46, 0.22, 0.075

LEGACY_SIZES = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}


def fmt(value):
    return f'{value:.2f}'.rstrip('0').rstrip('.')


class Glyphs:
    def __init__(self, path):
        self.font = TTFont(path)
        self.glyph_set = self.font.getGlyphSet()
        self.cmap = self.font.getBestCmap()

    def name(self, char):
        return self.cmap[ord(char)]

    def bounds(self, char):
        pen = BoundsPen(self.glyph_set)
        self.glyph_set[self.name(char)].draw(pen)
        return pen.bounds

    def advance(self, char):
        return self.font['hmtx'][self.name(char)][0]

    def path(self, char, scale, dx, dy):
        """SVG path data, font units → canvas (y flipped), then translated."""
        pen = SVGPathPen(self.glyph_set, ntos=fmt)
        self.glyph_set[self.name(char)].draw(
            TransformPen(pen, (scale, 0, 0, -scale, dx, dy))
        )
        return pen.getCommands()


class TornK:
    """Geometry of the mark inside a square canvas of [size] units."""

    def __init__(self, glyphs, size=CANVAS, height=MARK_HEIGHT):
        x_min, y_min, x_max, y_max = glyphs.bounds('K')
        self.scale = height / (y_max - y_min)
        self.width = (x_max - x_min) * self.scale
        self.height = height
        self.left = (size - self.width) / 2
        self.top = (size - height) / 2
        self.size = size
        # Pen origin (left side bearing, baseline) that puts the K's bounding
        # box at (left, top).
        self.origin = (self.left - x_min * self.scale, self.top + y_max * self.scale)
        self.path = glyphs.path('K', self.scale, *self.origin)

    def cut_y(self, x):
        y_left = self.top + self.height * CUT_LEFT
        y_right = self.top + self.height * CUT_RIGHT
        return y_left + (y_right - y_left) * (x - self.left) / self.width

    @property
    def half_gap(self):
        return self.height * CUT_GAP / 2

    def upper_region(self):
        s, g = self.size, self.half_gap
        return [(0, 0), (s, 0), (s, self.cut_y(s) - g), (0, self.cut_y(0) - g)]

    def lower_region(self):
        s, g = self.size, self.half_gap
        return [(0, self.cut_y(0) + g), (s, self.cut_y(s) + g), (s, s), (0, s)]


def polygon_path(points):
    head, *rest = points
    return f'M{fmt(head[0])},{fmt(head[1])} ' + ' '.join(
        f'L{fmt(x)},{fmt(y)}' for x, y in rest
    ) + ' Z'


def mark_vector(mark, color):
    groups = ''.join(
        f'''
    <group>
        <clip-path android:pathData="{polygon_path(region)}" />
        <path
            android:fillColor="{color}"
            android:pathData="{mark.path}" />
    </group>'''
        for region in (mark.upper_region(), mark.lower_region())
    )
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.py — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{fmt(CANVAS)}dp"
    android:height="{fmt(CANVAS)}dp"
    android:viewportWidth="{fmt(CANVAS)}"
    android:viewportHeight="{fmt(CANVAS)}">{groups}
</vector>
'''


def wordmark_vector(glyphs, text='Koyak', height=18.0, tracking=-0.02):
    """Wordmark centred in a 200x80dp splash branding box."""
    box_w, box_h = 200.0, 80.0
    cap = glyphs.bounds('K')[3]
    scale = height / cap
    spacing = tracking * height

    advances = [glyphs.advance(c) * scale for c in text]
    total = sum(advances) + spacing * (len(text) - 1)
    x = (box_w - total) / 2
    baseline = (box_h + height) / 2

    paths = []
    for char, advance in zip(text, advances):
        paths.append(glyphs.path(char, scale, x, baseline))
        x += advance + spacing
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.py — do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{fmt(box_w)}dp"
    android:height="{fmt(box_h)}dp"
    android:viewportWidth="{fmt(box_w)}"
    android:viewportHeight="{fmt(box_h)}">
    <path
        android:fillColor="{MUTED}"
        android:pathData="{' '.join(paths)}" />
</vector>
'''


def legacy_png(glyphs, px, supersample=4):
    """Pre-Android-8 launcher icon: rounded square with the mark."""
    size = px * supersample
    # Legacy icons have no mask, so the mark sits a little larger.
    mark = TornK(glyphs, size=size, height=size * 0.5)

    units_per_em = glyphs.font['head'].unitsPerEm
    font = ImageFont.truetype(str(FONT), round(mark.scale * units_per_em))
    glyph = Image.new('L', (size, size), 0)
    ImageDraw.Draw(glyph).text(mark.origin, 'K', font=font, fill=255, anchor='ls')

    upper = Image.new('L', (size, size), 0)
    ImageDraw.Draw(upper).polygon(mark.upper_region(), fill=255)
    lower = Image.new('L', (size, size), 0)
    ImageDraw.Draw(lower).polygon(mark.lower_region(), fill=255)
    mark_mask = ImageChops.lighter(
        ImageChops.multiply(glyph, upper),
        ImageChops.multiply(glyph, lower),
    )

    tile = Image.new('L', (size, size), 0)
    inset = size * 0.04
    ImageDraw.Draw(tile).rounded_rectangle(
        (inset, inset, size - inset, size - inset), radius=size * 0.22, fill=255
    )
    icon = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    icon.paste(_rgb(BACKGROUND), (0, 0), tile)
    icon.paste(_rgb(GREEN), (0, 0), ImageChops.multiply(mark_mask, tile))
    return icon.resize((px, px), Image.LANCZOS)


def _rgb(hex_color):
    return tuple(int(hex_color[i:i + 2], 16) for i in (1, 3, 5))


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f'wrote {path.relative_to(ROOT)}')


def main():
    glyphs = Glyphs(FONT)
    mark = TornK(glyphs)

    write(RES / 'drawable/ic_launcher_foreground.xml', mark_vector(mark, GREEN))
    write(RES / 'drawable/ic_launcher_monochrome.xml', mark_vector(mark, '#FFFFFFFF'))
    # Android 12+ draws the splash icon on a 288dp canvas; a smaller mark
    # keeps the K around 80dp tall there (and in the pre-12 layer-list).
    splash_mark = TornK(glyphs, height=SPLASH_MARK_HEIGHT)
    write(RES / 'drawable/splash_icon.xml', mark_vector(splash_mark, GREEN))
    write(RES / 'drawable/splash_branding.xml', wordmark_vector(glyphs))

    for density, px in LEGACY_SIZES.items():
        target = RES / f'mipmap-{density}/ic_launcher.png'
        legacy_png(glyphs, px).save(target)
        print(f'wrote {target.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
